version: '3'
services:
  web:
    container_name: camera-web
    image: camera-web
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    container_name: demo-postgres
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=springboot