aiservier:
  ip: 0.0.0.0
  port: 5353
  contextpath: /api/camera_detect

rtsp:
  username: username
  password: password
  pattern: rtsp://${rtsp.username}:${rtsp.password}%s/Src/MediaInput/hevc

xware-videoserver:
  url: https://www.xware.co.jp

authorities:
  - authority: ROLE_ROOT
    displayname: ルート
    weight: 4
  - authority: ROLE_ADMIN
    displayname: 管理者
    weight: 2
  - authority: ROLE_USER
    displayname: 一般ユーザー
    weight: 1

root:
  email: evadcmd@gmail.com
  password: root
  username: root
  enabled: true

RSA:
  public: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt01+dqecRH8ip4Tbw0AONauBQGpD+iornM5jaGhupcB1AvB1Df2rUeCep7VU3obCRoHxAmMQeygvtFG0Yytv4dQS92MSL634/Tn7SBpEQh1zw3CnREBgV5Y/Xjc0mrpeiRV+1ec6uVdJBUof6dL7tvi6MZg4XggzhfQaKedH2p98heMvhiz3XgTzSv68wEVW9YOZdQ4QIhriyV3xLZA2aTMW5HGcOVxlAF4A8TLkBH9r7wM0Lt9PQmMeI6ZdzLLqGh4D+qOvDMzxGm/WoegdfrP+vqzjJ1mV5pgA5O0YuGDQYSsHuh+qzgZT+J5K8etbgGexNGTqPTWKiCjgTXDL4wIDAQAB
  private: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3TX52p5xEfyKnhNvDQA41q4FAakP6KiuczmNoaG6lwHUC8HUN/atR4J6ntVTehsJGgfECYxB7KC+0UbRjK2/h1BL3YxIvrfj9OftIGkRCHXPDcKdEQGBXlj9eNzSaul6JFX7V5zq5V0kFSh/p0vu2+LoxmDheCDOF9Bop50fan3yF4y+GLPdeBPNK/rzARVb1g5l1DhAiGuLJXfEtkDZpMxbkcZw5XGUAXgDxMuQEf2vvAzQu309CYx4jpl3MsuoaHgP6o68MzPEab9ah6B1+s/6+rOMnWZXmmADk7Ri4YNBhKwe6H6rOBlP4nkrx61uAZ7E0ZOo9NYqIKOBNcMvjAgMBAAECggEAJrFbApz65ZKYtBfdc+evmDCtxfUoiEQilKUUYtO4l5B6orYzX1KuuUfa9bfXRGnZ1JxVTZWvwu+Gsl+U3mIq6dakckgdbKciqgF1Q5EX24TwDM9Y35VfQN3cXnz0w7yXfARnk6uNv9Xm+hDdj7QToln6o8FoFKFSjvIqG7JQfptUa8mr4XrZj04L9y8Xp+xnD2/HBLyWWRuVlxjvv82e26M36CmekQtE4QDVVzmRTA2TSWgQulha/HsngTig/Qei2di3DVqDsO45quZgqE4uelHfdTRdOpm3sSNgrwDmmqgdhSZ7qaMGaBfaQ7tKYtE+yIJUf6F5fjBnoZVEQalQQQKBgQDcjhnMZHdiTt9N+iU0FsPyKktPaIv6GeChhaNVjFTSIqe8osjVQrsUNgqAsapxaE6U8HJPvgIOS73jdhlvemXPtOeKa6+z0Vs0irj1tfoQOLft5e4f21f1Xn5Ij76rxlTw6D70OExxL14gzYen2Gcm1KNjrXQUTCYNR+Lh0rXm8wKBgQDUwslIRyZxv56I5/rmzCVeNX9zmhRnkkbvwV55RUXtaY39HPQwzOwwU8mhoV8PgO9hgXI+z/XqO6FE9bfSbAx8QpRHe3Tn4tffs0fIL6SlYFRW4xyAebvIhh5/Z2XpRWrNDglWFhzM+VPPUoM5GavZ46sw9La1c+5B4wcnUlKjUQKBgQCDxFnhZPx2PUzoF1R2xEsYuO/5ZyqJp0Au/9pPV+GtEYtJBbAayR1fu9GWhY6g5oJcNTL2NTyhMdsms/4KPgPpjdjvN9rnAWMOBvrtwWS+oEQy2zXiznbEX0nvLAHsOjexHe/OlHwG+xevXVt4ia9G4a8j9BLvtXbeZF5GME8AxQKBgDjvj3HaKH2UK9azTb9pri5R3rOO7hrxWC5c7u1BDn+EGc08bFSK4kHkijbIummptWXAgFQyzrpKDtQndXPIGmc+YfPnI9fSKrbggTsfFM50wt0llcED0q7MxWiOwQT14KjTMshoznhD2JvIlvk213hNpshJFIPmbEIRgR6Sty6hAoGBAJR0HrpocoPWHs0Kn5WikXU6V/iUEwDpAZ8DWfV1y4PtbVgB9Uje+3f3ztVLm85LtkVWf/2ttVKGENGARpOFSMnSaV1/lh+mhq5kJCWWzsLAfJPXEQKZYwm3sHPP2QgX/Hw6ps1U41TKwIT3xpgycgOe1CNY0wQMDnngMYEwkWEk