server:
  port: 8080
  servlet: 
    context-path: /demo
    session:
      timeout: 30

spring:

  profiles:
    include:
      - config
  
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    # url: jdbc:postgresql://db:5432/springboot #　docker用設定
    driver-class-name: org.postgresql.Driver
    username: root
    password: root
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 20

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  quartz:
    properties:
      org:
        quartz:
          scheduler:
            overwriteExistingjobs: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: evadcmd@gmail.com
    password: undefined
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
